; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = SolarArrayMainFrame

[env:BuoyMainFrame]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<BuoyMainFrame/*>
lib_deps = 
	SPI @ ^1.0
	Wire
	arduino-libraries/SD@^1.3.0
	seeed-studio/Grove barometer HP20x@^1.0.0
	northernwidget/DS3231@^1.1.2
	waspinator/AccelStepper@^1.64
	bluerobotics/BlueRobotics Keller LD Library@^1.1.2

[env:CannisterMainFrame]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<CannisterMainFrame/*>
lib_deps = 
	SPI @ ^1.0
	seeed-studio/Grove barometer HP20x@^1.0.0
	Wire
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	adafruit/Adafruit ADS1X15@^2.5.0
	bluerobotics/BlueRobotics TSYS01 Library@^1.0.1
	bluerobotics/BlueRobotics Keller LD Library@^1.1.2

[env:SolarArrayMainFrame]
platform = atmelmegaavr
board = nano_every
framework = arduino
build_src_filter = +<SolarArrayMainFrame/*>
lib_deps = 
